/**
 * Base de datos de recetas — 100+ recetas saludables en español rioplatense.
 */

export interface Recipe {
  name: string;
  category: "desayuno" | "almuerzo" | "cena" | "snack" | "postre" | "bebida";
  calories?: number;
  protein?: number;
  carbs?: number;
  fats?: number;
  prepTime: string;
  servings: number;
  ingredients: string[];
  steps: string[];
  tip?: string;
  tags?: string[];
}

// ── DESAYUNOS ─────────────────────────────────────────────────────
export const BREAKFAST_RECIPES: Recipe[] = [
  {
    name: "Bowl de Avena con Fruta y Semillas",
    category: "desayuno",
    calories: 380, protein: 14, carbs: 58, fats: 10,
    prepTime: "5 min",
    servings: 1,
    ingredients: [
      "1 taza (90g) de avena arrollada",
      "300 ml de leche descremada o bebida vegetal",
      "1 banana en rodajas",
      "1 puñado de frutillas (frescos o congelados)",
      "1 cucharada de semillas de chía",
      "1 cucharadita de miel",
      "Canela a gusto",
    ],
    steps: [
      "Calentá la leche en una ollita a fuego medio.",
      "Agregá la avena y revolvé constantemente por 5 minutos hasta espesar.",
      "Volcá en un bowl y decorá con la banana, las frutillas y las semillas.",
      "Rociá con la miel y espolvorea canela.",
    ],
    tip: "Podés preparar overnight oats la noche anterior para ahorrar tiempo.",
    tags: ["alto en fibra", "sin gluten (avena certificada)", "post-entreno"],
  },
  {
    name: "Tostadas con Palta y Huevo Pochado",
    category: "desayuno",
    calories: 420, protein: 20, carbs: 35, fats: 22,
    prepTime: "10 min",
    servings: 1,
    ingredients: [
      "2 rebanadas de pan integral",
      "1 palta (aguacate) madura",
      "2 huevos",
      "Jugo de 1/2 limón",
      "Sal, pimienta y pimentón ahumado",
      "Opcional: semillas de sésamo y ciboulette",
    ],
    steps: [
      "Tostar el pan.",
      "Pisá la palta con el limón, sal y pimienta hasta obtener una pasta suave.",
      "Pochá los huevos: hervir agua, agregar un chorro de vinagre, crear un remolino y sumergir el huevo por 3 minutos.",
      "Untá la palta sobre las tostadas, colocá el huevo pochado encima.",
      "Condimentá con pimentón y semillas.",
    ],
    tip: "La palta es rica en grasas saludables que te mantienen saciado hasta el mediodía.",
    tags: ["rico en proteínas", "grasas saludables"],
  },
  {
    name: "Pancakes de Banana y Avena",
    category: "desayuno",
    calories: 340, protein: 18, carbs: 48, fats: 7,
    prepTime: "15 min",
    servings: 2,
    ingredients: [
      "2 bananas maduras",
      "2 huevos",
      "1 taza de avena",
      "1/2 cucharadita de polvo de hornear",
      "1 cucharadita de esencia de vainilla",
      "Aceite de coco o rocío vegetal",
    ],
    steps: [
      "Pisá las bananas en un bowl hasta hacer un puré.",
      "Batí los huevos e incorporalos al puré.",
      "Agregá la avena, el polvo de hornear y la vainilla. Mezclá bien.",
      "Calentá una sartén antiadherente con un poco de aceite.",
      "Volcá 2-3 cucharadas de mezcla por panqueque. Cocinás 2 min por lado.",
    ],
    tip: "Servir con fruta fresca y una cucharada de yogur griego en lugar de dulce de leche.",
    tags: ["sin azúcar añadida", "alto en fibra", "sin gluten"],
  },
  {
    name: "Yogur Griego con Granola y Fruta Fresca",
    category: "desayuno",
    calories: 320, protein: 22, carbs: 40, fats: 8,
    prepTime: "3 min",
    servings: 1,
    ingredients: [
      "200g de yogur griego natural (0% o entero)",
      "30g de granola sin azúcar añadida",
      "1 kiwi en rodajas",
      "1 puñado de arándanos",
      "1 cucharadita de miel",
    ],
    steps: [
      "Ponés el yogur en un bowl.",
      "Agregás la granola, el kiwi y los arándanos.",
      "Rociás con la miel.",
    ],
    tip: "El yogur griego tiene el doble de proteínas que el yogur común. Buscá opciones sin azúcar añadida.",
    tags: ["alto en proteínas", "rico en probióticos", "rápido"],
  },
  {
    name: "Revuelto de Claras con Verduras",
    category: "desayuno",
    calories: 280, protein: 28, carbs: 12, fats: 12,
    prepTime: "10 min",
    servings: 1,
    ingredients: [
      "6 claras de huevo (o 3 huevos enteros)",
      "1/2 pimiento rojo picado",
      "1/2 cebolla picada",
      "1 puñado de espinaca",
      "2 rodajas de tomate",
      "1 cucharadita de aceite de oliva",
      "Sal, pimienta, cúrcuma y orégano",
    ],
    steps: [
      "Calentá el aceite en una sartén a fuego medio.",
      "Salteá la cebolla y el pimiento por 3 minutos.",
      "Agregá la espinaca y revolvé hasta que se reduzca.",
      "Batí las claras, sazonás y volcás sobre las verduras.",
      "Revolvés suavemente hasta que cuaje. Servís con el tomate.",
    ],
    tip: "Altísimo en proteínas, bajo en calorías. Ideal pre-competencia o si estás en déficit calórico.",
    tags: ["alto en proteínas", "bajo en calorías", "sin carbohidratos"],
  },
  {
    name: "Smoothie Verde Energizante",
    category: "desayuno",
    calories: 290, protein: 12, carbs: 45, fats: 6,
    prepTime: "5 min",
    servings: 1,
    ingredients: [
      "2 tazas de espinaca fresca",
      "1 banana congelada",
      "1/2 manzana verde",
      "1 cucharada de semillas de lino",
      "200ml de agua de coco o agua fría",
      "Jugo de 1/2 limón",
    ],
    steps: [
      "Poné todos los ingredientes en la licuadora.",
      "Licuás a velocidad alta por 60 segundos hasta obtener una mezcla suave.",
      "Servís inmediatamente.",
    ],
    tip: "La banana congelada le da cremosidad sin necesidad de agregar yogur.",
    tags: ["vegano", "fácil de digerir", "hidratante"],
  },
  {
    name: "Budín de Semillas de Chía",
    category: "desayuno",
    calories: 310, protein: 11, carbs: 32, fats: 14,
    prepTime: "5 min + 4h reposo",
    servings: 2,
    ingredients: [
      "6 cucharadas de semillas de chía",
      "500ml de leche vegetal sin azúcar",
      "1 cucharadita de extracto de vainilla",
      "1 cucharadita de miel o sirope de agave",
      "Fruta para acompañar: mango, frambuesas o banana",
    ],
    steps: [
      "Mezclá la chía con la leche, vainilla y endulzante en un frasco.",
      "Revolvé bien para que no se formen grumos.",
      "Tapás y guardás en la heladera al menos 4 horas o toda la noche.",
      "Al servir, decorás con la fruta elegida.",
    ],
    tip: "Preparalo la noche anterior para tener el desayuno listo al despertar.",
    tags: ["vegano", "alto en omega-3", "sin gluten", "preparación anticipada"],
  },
];

// ── ALMUERZOS ─────────────────────────────────────────────────────
export const LUNCH_RECIPES: Recipe[] = [
  {
    name: "Bowl de Pollo a la Plancha con Quinoa y Verduras",
    category: "almuerzo",
    calories: 490, protein: 42, carbs: 45, fats: 12,
    prepTime: "25 min",
    servings: 2,
    ingredients: [
      "300g de pechuga de pollo",
      "1 taza de quinoa cocida",
      "1 taza de garbanzos cocidos",
      "2 tazas de rúcula",
      "1 pepino",
      "1 palta",
      "Para el aderezo: 2 cdas de aceite de oliva, limón, ajo, mostaza",
    ],
    steps: [
      "Sazoná el pollo con sal, pimienta, ajo en polvo y pimentón. Cocinarlo a la plancha 5-6 min por lado.",
      "Cocinás la quinoa según el envase (2 partes agua : 1 parte quinoa).",
      "Mezclás los ingredientes del aderezo en un frasco y agitás.",
      "Armás el bowl: quinoa de base, rúcula, pepino, palta, garbanzos.",
      "Cortás el pollo en tiras y lo ponés encima. Rociás el aderezo.",
    ],
    tip: "La quinoa es una proteína completa. Combinada con el pollo y los garbanzos, este plato tiene un perfil aminoacídico excelente.",
    tags: ["alto en proteínas", "meal prep", "sin gluten"],
  },
  {
    name: "Tapa de Asado al Horno con Batata y Ensalada",
    category: "almuerzo",
    calories: 520, protein: 38, carbs: 40, fats: 18,
    prepTime: "50 min",
    servings: 3,
    ingredients: [
      "600g de tapa de asado o peceto",
      "3 batatas medianas",
      "Romero, tomillo, ajo",
      "Aceite de oliva, sal gruesa",
      "Para ensalada: tomate, lechuga, zanahoria rallada, aceitunas",
    ],
    steps: [
      "Precalentá el horno a 200°C.",
      "Cortá las batatas en gajos, condimentalas con aceite, sal y romero. Horneá 30 min.",
      "Sellá la carne en sartén bien caliente 2 min por lado. Pasala al horno 20 min.",
      "Dejá reposar la carne 5 minutos antes de cortar.",
      "Servís con la ensalada fresca y las batatas.",
    ],
    tip: "La batata tiene índice glucémico más bajo que la papa y es rica en vitamina A.",
    tags: ["rico en hierro", "sin gluten"],
  },
  {
    name: "Lenteja Estofada con Verduras",
    category: "almuerzo",
    calories: 380, protein: 22, carbs: 55, fats: 6,
    prepTime: "35 min",
    servings: 4,
    ingredients: [
      "2 tazas de lentejas secas (400g)",
      "2 zanahorias en cubos",
      "2 papas en cubos",
      "1 cebolla grande picada",
      "4 dientes de ajo picados",
      "2 cucharadas de extracto de tomate",
      "Comino, cúrcuma, laurel, sal",
      "1 litro de caldo de verduras",
    ],
    steps: [
      "Remojá las lentejas 1 hora (o usá lentejas sin remojar y agregá 15 min de cocción).",
      "Salteá la cebolla y el ajo hasta dorar.",
      "Agregá las zanahorias, las papas y el extracto de tomate. Revolvés.",
      "Incorporá las lentejas, el caldo y las especias. Cocción 25-30 minutos.",
      "Rectificás sazón y servís.",
    ],
    tip: "Excelente fuente vegetal de hierro. Combinalo con alimentos ricos en vitamina C para mejorar la absorción.",
    tags: ["vegano", "alto en hierro", "económico", "meal prep"],
  },
  {
    name: "Salmón al Limón con Arroz Integral y Brócoli",
    category: "almuerzo",
    calories: 510, protein: 44, carbs: 42, fats: 18,
    prepTime: "30 min",
    servings: 2,
    ingredients: [
      "2 filetes de salmón (150g c/u)",
      "1 taza de arroz integral cocido",
      "300g de brócoli",
      "Jugo de 2 limones",
      "2 cucharadas de aceite de oliva",
      "Ajo, eneldo, sal y pimienta",
    ],
    steps: [
      "Marinás el salmón con limón, aceite, ajo y eneldo 15 minutos.",
      "Cocinás el salmón en sartén 4 min por lado a fuego medio-alto.",
      "Cocé el brócoli al vapor 5-7 minutos.",
      "Servís el salmón sobre el arroz con el brócoli al costado.",
    ],
    tip: "El salmón es una de las mejores fuentes de omega-3. Dos porciones semanales son la recomendación.",
    tags: ["alto en omega-3", "sin gluten"],
  },
  {
    name: "Ensalada Completa de Atún",
    category: "almuerzo",
    calories: 360, protein: 34, carbs: 28, fats: 12,
    prepTime: "10 min",
    servings: 1,
    ingredients: [
      "2 latas de atún al natural (320g)",
      "2 huevos duros en cuartos",
      "1 lata de garbanzos (200g)",
      "1/2 pimiento rojo",
      "1/2 cebolla morada en juliana fina",
      "Aceitunas verdes",
      "Aceite de oliva, limón, sal",
    ],
    steps: [
      "Escurrís el atún y los garbanzos.",
      "Mezclás todos los ingredientes en una ensaladera.",
      "Aderezás con aceite, limón y sal.",
    ],
    tip: "Preparalo en un tupper y llevalo al trabajo. Sin cocción, listo en minutos.",
    tags: ["rápido", "meal prep", "sin gluten"],
  },
  {
    name: "Milanesa de Pollo al Horno con Puré de Zapallo",
    category: "almuerzo",
    calories: 450, protein: 40, carbs: 38, fats: 14,
    prepTime: "35 min",
    servings: 2,
    ingredients: [
      "300g de pechuga de pollo aplastada",
      "1/2 kg de zapallo",
      "2 huevos",
      "Pan rallado integral",
      "Ajo en polvo, orégano, sal",
      "Leche vegetal, nuez moscada",
    ],
    steps: [
      "Precalentá el horno a 200°C.",
      "Pasá las pechugas por huevo batido y pan rallado sazonado.",
      "Colocás en placa aceitada y horneás 20 min dando vuelta a mitad.",
      "Cocinás el zapallo al vapor, pisás con leche, sal y nuez moscada.",
    ],
    tip: "Al horno tiene mucho menos grasa que frita pero el mismo sabor si el pan rallado está bien sazonado.",
    tags: ["alto en proteínas", "sin fritos"],
  },
];

// ── CENAS ─────────────────────────────────────────────────────────
export const DINNER_RECIPES: Recipe[] = [
  {
    name: "Revuelto de Verduras y Huevo con Tostadas Integrales",
    category: "cena",
    calories: 330, protein: 24, carbs: 28, fats: 14,
    prepTime: "15 min",
    servings: 1,
    ingredients: [
      "3 huevos",
      "1/2 pimiento",
      "1 zapallito verde",
      "1 puñado de espinaca",
      "1 cebolla de verdeo",
      "2 rebanadas de pan integral",
      "Aceite de oliva, sal, cúrcuma",
    ],
    steps: [
      "Salteá las verduras en aceite de oliva 5 minutos.",
      "Batí los huevos con sal y cúrcuma.",
      "Volcalos sobre las verduras y revolvés hasta cuajar.",
      "Servís con las tostadas.",
    ],
    tip: "La cena no debería ser la comida más pesada del día. Este plato es completo y digestivo.",
    tags: ["rápido", "vegetariano"],
  },
  {
    name: "Wok de Pollo con Fideos de Arroz y Verduras",
    category: "cena",
    calories: 420, protein: 36, carbs: 48, fats: 10,
    prepTime: "20 min",
    servings: 2,
    ingredients: [
      "250g de pechuga de pollo en tiras",
      "150g de fideos de arroz",
      "2 tazas de brócoli",
      "1 pimiento rojo",
      "1 zanahoria en juliana",
      "3 cucharadas de salsa de soja baja en sodio",
      "Jengibre fresco rallado, ajo",
      "Semillas de sésamo",
    ],
    steps: [
      "Hidratá los fideos según el paquete.",
      "Calentá el wok o sartén grande a fuego muy alto.",
      "Salteá el pollo 4 minutos. Retirás.",
      "En el mismo wok salteás las verduras 3-4 minutos.",
      "Volvés a incorporar el pollo y los fideos. Agregás la salsa de soja y el jengibre.",
      "Revolvés 1-2 minutos más. Decorás con sésamo.",
    ],
    tip: "El secreto del wok es el fuego muy alto y movimiento constante. Todo el proceso no tarda más de 10 minutos.",
    tags: ["sin gluten", "alto en proteínas"],
  },
  {
    name: "Cazuela de Vegetales con Arroz",
    category: "cena",
    calories: 310, protein: 10, carbs: 56, fats: 7,
    prepTime: "30 min",
    servings: 3,
    ingredients: [
      "1 taza de arroz integral",
      "2 zanahorias",
      "2 papas medianas",
      "1 choclo desgranado",
      "1 lata de tomates triturados (400g)",
      "Cebolla, ajo, pimentón dulce, sal",
    ],
    steps: [
      "Salteá cebolla y ajo. Agregá zanahoria y papa en cubos.",
      "Incorporá el tomate, el choclo y el arroz.",
      "Cubrís con agua o caldo y cocinás a fuego bajo 25 minutos.",
      "Rectificá sazón y servís.",
    ],
    tip: "Plato económico, nutritivo y reconfortante. Perfecto para el invierno.",
    tags: ["vegano", "económico"],
  },
  {
    name: "Merluza al Horno con Papas y Limón",
    category: "cena",
    calories: 380, protein: 34, carbs: 35, fats: 10,
    prepTime: "35 min",
    servings: 2,
    ingredients: [
      "2 filetes de merluza (200g c/u)",
      "2 papas medianas en rodajas finas",
      "1 cebolla en aros",
      "2 limones",
      "Perejil, ajo, aceite de oliva, sal",
    ],
    steps: [
      "Precalentá el horno a 200°C.",
      "Ponés una cama de papas y cebollas en una fuente. Salás y rociás con aceite.",
      "Horneás 15 min las papas.",
      "Colocás la merluza encima, rociás con limón, ajo y perejil.",
      "Otros 15-20 min en el horno hasta que el pescado esté cocido.",
    ],
    tip: "El pescado blanco es una proteína magra excelente para la cena. Fácil de digerir antes de dormir.",
    tags: ["bajo en grasas", "sin gluten"],
  },
  {
    name: "Tortilla de Papas Saludable",
    category: "cena",
    calories: 350, protein: 18, carbs: 35, fats: 16,
    prepTime: "30 min",
    servings: 2,
    ingredients: [
      "3 papas medianas",
      "5 huevos",
      "1 cebolla",
      "Aceite de oliva",
      "Sal, pimienta, perejil",
    ],
    steps: [
      "Cocinás las papas en cubos al microondas 8 min o hervís.",
      "Salteás la cebolla hasta transparentar.",
      "Batís los huevos, mezclás con papa y cebolla.",
      "Cocinás en sartén tapada a fuego bajo 10 min. Dás vuelta con un plato.",
      "Cocinás otros 5 min del otro lado.",
    ],
    tip: "La tortilla hecha con papas cocidas y poco aceite tiene muchas menos calorías que la tradicional.",
    tags: ["vegetariano", "económico"],
  },
];

// ── SNACKS ────────────────────────────────────────────────────────
export const SNACK_RECIPES: Recipe[] = [
  {
    name: "Bola de Proteína (Energy Ball)",
    category: "snack",
    calories: 120, protein: 5, carbs: 14, fats: 6,
    prepTime: "15 min + 30 min heladera",
    servings: 12,
    ingredients: [
      "1 taza de avena",
      "1/2 taza de mantequilla de maní sin azúcar",
      "3 cucharadas de miel",
      "2 cucharadas de semillas de chía",
      "1/2 taza de chips de chocolate amargo",
      "1 cucharadita de vainilla",
    ],
    steps: [
      "Mezclás todos los ingredientes en un bowl.",
      "Refrigerás 30 minutos para que la mezcla sea más manejable.",
      "Formás bolitas del tamaño de una pelota de golf.",
      "Guardás en un recipiente hermético en la heladera hasta 1 semana.",
    ],
    tip: "Perfectas para llevar al trabajo o como pre-entreno rápido.",
    tags: ["sin azúcar refinada", "alto en fibra"],
  },
  {
    name: "Hummus Casero con Crudités",
    category: "snack",
    calories: 180, protein: 8, carbs: 20, fats: 8,
    prepTime: "10 min",
    servings: 4,
    ingredients: [
      "1 lata de garbanzos (400g)",
      "2 cucharadas de tahini (pasta de sésamo)",
      "Jugo de 1 limón",
      "1 diente de ajo",
      "2 cucharadas de aceite de oliva",
      "Sal, cúrcuma y pimentón",
      "Para acompañar: zanahoria, apio, pepino",
    ],
    steps: [
      "Escurrís los garbanzos reservando el líquido.",
      "Procesás garbanzos, tahini, limón, ajo y aceite en licuadora.",
      "Agregás líquido de los garbanzos para ajustar textura.",
      "Sazonás y servís con las verduras crudas.",
    ],
    tip: "El agua de garbanzos (aquafaba) hace el hummus más cremoso. También se puede congelar.",
    tags: ["vegano", "sin gluten", "alto en proteínas vegetales"],
  },
  {
    name: "Licuado de Proteínas Casero",
    category: "snack",
    calories: 280, protein: 25, carbs: 30, fats: 6,
    prepTime: "5 min",
    servings: 1,
    ingredients: [
      "1 taza de leche descremada o bebida vegetal",
      "1 scoop de proteína en polvo (sabor chocolate)",
      "1 banana congelada",
      "1 cucharada de cacao amargo",
      "1 cucharada de mantequilla de maní",
      "Hielo opcional",
    ],
    steps: [
      "Ponés todos los ingredientes en la licuadora.",
      "Licuás hasta obtener una textura cremosa.",
      "Consumís dentro de los 30 minutos para mayor absorción.",
    ],
    tip: "Ideal como post-entreno. Si no tenés proteína en polvo, agregá un huevo cocido o yogur griego.",
    tags: ["post-entreno", "alto en proteínas"],
  },
  {
    name: "Manzana con Mantequilla de Maní",
    category: "snack",
    calories: 210, protein: 5, carbs: 28, fats: 10,
    prepTime: "2 min",
    servings: 1,
    ingredients: [
      "1 manzana grande",
      "2 cucharadas de mantequilla de maní natural",
    ],
    steps: [
      "Cortás la manzana en gajos.",
      "Sumergís en la mantequilla de maní.",
    ],
    tip: "Combinación perfecta: carbohidrato de la manzana + proteína y grasa del maní = saciedad prolongada.",
    tags: ["rápido", "vegano"],
  },
  {
    name: "Chips de Kale al Horno",
    category: "snack",
    calories: 80, protein: 4, carbs: 8, fats: 4,
    prepTime: "20 min",
    servings: 2,
    ingredients: [
      "1 manojo de kale (col rizada)",
      "1 cucharada de aceite de oliva",
      "Sal, ajo en polvo, levadura nutricional (opcional)",
    ],
    steps: [
      "Precalentá el horno a 150°C.",
      "Lavás y secás muy bien el kale. Lo separás en trozos pequeños.",
      "Masajeás con aceite y los condimentos.",
      "Extendés en placa y horneás 15-20 min hasta que esté crujiente.",
    ],
    tip: "El secreto es el horno bajo y el kale perfectamente seco. Si está húmedo, se cocina al vapor y no queda crujiente.",
    tags: ["bajo en calorías", "vegano", "crujiente"],
  },
  {
    name: "Edamames con Sal Marina",
    category: "snack",
    calories: 150, protein: 12, carbs: 12, fats: 5,
    prepTime: "5 min",
    servings: 1,
    ingredients: [
      "200g de edamames (soja en vaina, congelados)",
      "Sal marina gruesa",
    ],
    steps: [
      "Hervís los edamames congelados 3-4 minutos.",
      "Escurrís y espolvoreas con sal marina.",
    ],
    tip: "Los edamames son una de las fuentes vegetales de proteína completa más accesibles. Buscalos congelados.",
    tags: ["vegano", "sin gluten", "alto en proteínas"],
  },
];

// ── POSTRES SALUDABLES ────────────────────────────────────────────
export const DESSERT_RECIPES: Recipe[] = [
  {
    name: "Mousse de Chocolate y Aguacate",
    category: "postre",
    calories: 280, protein: 5, carbs: 28, fats: 18,
    prepTime: "10 min + 1h heladera",
    servings: 4,
    ingredients: [
      "2 paltas maduras",
      "4 cucharadas de cacao amargo en polvo",
      "3 cucharadas de miel o sirope de agave",
      "1 cucharadita de esencia de vainilla",
      "Una pizca de sal",
      "Frambuesas para decorar",
    ],
    steps: [
      "Procesás la palta, el cacao, la miel, la vainilla y la sal hasta obtener una crema muy suave.",
      "Refrigerás al menos 1 hora.",
      "Servís en copas con frambuesas.",
    ],
    tip: "Sorprendente: nadie adivina que la base es palta. La textura es de una mousse de lujo.",
    tags: ["sin gluten", "vegano", "sin azúcar refinada"],
  },
  {
    name: "Brownies de Poroto Negro",
    category: "postre",
    calories: 190, protein: 8, carbs: 28, fats: 6,
    prepTime: "35 min",
    servings: 12,
    ingredients: [
      "1 lata de porotos negros (400g), escurridos y enjuagados",
      "2 huevos",
      "4 cucharadas de cacao amargo",
      "1/4 taza de miel",
      "1 cucharadita de polvo de hornear",
      "1 cucharadita de vainilla",
      "Una pizca de sal",
      "50g de chips de chocolate amargo (opcional)",
    ],
    steps: [
      "Precalentá el horno a 175°C.",
      "Procesás los porotos hasta obtener una pasta suave.",
      "Mezclás con el resto de los ingredientes.",
      "Volcás en molde cuadrado engrasado y horneas 25 minutos.",
      "Dejás enfriar antes de cortar.",
    ],
    tip: "Los porotos aportan proteínas y fibra. El sabor a frijol desaparece completamente con el cacao.",
    tags: ["sin gluten", "alto en fibra", "alto en proteínas"],
  },
  {
    name: "Helado de Banana en 1 Ingrediente",
    category: "postre",
    calories: 105, protein: 1, carbs: 27, fats: 0,
    prepTime: "5 min + 3h congelado",
    servings: 2,
    ingredients: [
      "3 bananas maduras",
      "Opcional: 1 cucharada de mantequilla de maní o cacao para mix-ins",
    ],
    steps: [
      "Cortás las bananas en rodajas y las congelás al menos 3 horas.",
      "Procesás en licuadora potente o procesador hasta obtener una crema.",
      "Consumís inmediatamente (helado soft) o volvés a congelar 1 hora.",
    ],
    tip: "Bananas muy maduras con puntos marrones dan el resultado más dulce y cremoso.",
    tags: ["vegano", "sin azúcar añadida", "sin gluten", "1 ingrediente"],
  },
  {
    name: "Torta de Zanahoria y Coco (sin harina)",
    category: "postre",
    calories: 220, protein: 6, carbs: 24, fats: 12,
    prepTime: "45 min",
    servings: 8,
    ingredients: [
      "3 zanahorias ralladas finamente",
      "3 huevos",
      "1/2 taza de azúcar rubia o miel",
      "1 taza de harina de almendra",
      "1/2 taza de coco rallado",
      "1 cucharadita de canela, 1/2 de jengibre",
      "1 cucharadita de polvo de hornear",
    ],
    steps: [
      "Precalentá el horno a 175°C.",
      "Batís los huevos con el azúcar.",
      "Incorporás la zanahoria, el coco y los secos.",
      "Volcás en molde y horneás 35 minutos.",
    ],
    tip: "Húmeda y esponjosa naturalmente gracias a la zanahoria. No necesita cobertura.",
    tags: ["sin gluten", "sin trigo"],
  },
];

// ── BEBIDAS ───────────────────────────────────────────────────────
export const DRINK_RECIPES: Recipe[] = [
  {
    name: "Agua Saborizada con Fruta y Hierbas",
    category: "bebida",
    calories: 15, protein: 0, carbs: 4, fats: 0,
    prepTime: "5 min",
    servings: 4,
    ingredients: [
      "1 litro de agua fría",
      "1/2 pepino en rodajas",
      "Menta fresca",
      "1 limón en rodajas",
      "Hielo",
    ],
    steps: [
      "Combinás todos los ingredientes en una jarra.",
      "Refrigerás al menos 30 minutos para que los sabores se integren.",
    ],
    tip: "Hidratarse más fácil con agua saborizada. Sin azúcar y deliciosa.",
    tags: ["sin azúcar", "hidratante", "vegano"],
  },
  {
    name: "Golden Milk (Leche Dorada)",
    category: "bebida",
    calories: 130, protein: 4, carbs: 10, fats: 7,
    prepTime: "5 min",
    servings: 1,
    ingredients: [
      "250ml de leche de coco o almendra",
      "1 cucharadita de cúrcuma",
      "1/2 cucharadita de jengibre en polvo",
      "1 cucharadita de miel",
      "Una pizca de pimienta negra (activa la curcumina)",
    ],
    steps: [
      "Calentás la leche sin hervir.",
      "Disolvés las especias en un poco de leche fría antes de agregar al caliente.",
      "Mezclás bien, endulzás y servís.",
    ],
    tip: "La pimienta negra aumenta hasta un 2000% la absorción de curcumina. No omitas este paso.",
    tags: ["anti-inflamatorio", "sin gluten", "vegano"],
  },
  {
    name: "Proteína Shake Post-Entreno",
    category: "bebida",
    calories: 250, protein: 30, carbs: 22, fats: 4,
    prepTime: "2 min",
    servings: 1,
    ingredients: [
      "1 scoop de proteína en polvo (sabor vainilla o neutro)",
      "300ml de leche descremada",
      "1 cucharadita de miel",
      "Hielo (opcional)",
    ],
    steps: [
      "Mezclás todo en shaker o licuadora.",
      "Consumís dentro de los 30-45 minutos post-entrenamiento.",
    ],
    tip: "La ventana anabólica: máxima absorción de nutrientes las primeras horas post-entreno.",
    tags: ["post-entreno", "alto en proteínas"],
  },
];

// Export consolidado
export const RECIPE_POOL = {
  breakfast: BREAKFAST_RECIPES,
  lunch: LUNCH_RECIPES,
  dinner: DINNER_RECIPES,
  snacks: SNACK_RECIPES,
  desserts: DESSERT_RECIPES,
  drinks: DRINK_RECIPES,
  all: [
    ...BREAKFAST_RECIPES,
    ...LUNCH_RECIPES,
    ...DINNER_RECIPES,
    ...SNACK_RECIPES,
    ...DESSERT_RECIPES,
    ...DRINK_RECIPES,
  ],
};

/** Retorna N recetas del pool filtrando opcionalmente por categoría */
export function selectRecipes(pool: Recipe[], count: number): Recipe[] {
  // Simple deterministic rotation
  return pool.slice(0, count);
}
